# Generated by Django 2.2.10 on 2021-05-08 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cartes_Creditss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.IntegerField(null=True)),
                ('date_ouverture', models.DateTimeField(null=True)),
                ('solde', models.FloatField(null=True)),
                ('type_compte', models.CharField(choices=[('compte courant ', 'compte courant '), ('compte d’épargne', 'compte d’épargne')], max_length=100, null=True)),
                ('CarteCredit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cartes_Creditss.credit_card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
