# Generated by Django 2.2.10 on 2021-05-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='CarteCredit',
        ),
    ]
