# Generated by Django 2.2.10 on 2021-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptess', '0002_remove_account_cartecredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='etatCompte',
            field=models.BooleanField(default=False),
        ),
    ]
