# Generated by Django 2.2.10 on 2021-05-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credit_card',
            fields=[
                ('num_Carte_Credit', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('date_expiration', models.DateTimeField(null=True)),
                ('type_carte', models.CharField(choices=[('carte Visa', 'carte Visa'), ('carte MasterCard', 'carte MasterCard')], max_length=100, null=True)),
            ],
        ),
    ]
