# Generated by Django 2.2.10 on 2021-05-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartes_Creditss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='num_Carte_Credit',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
