# Generated by Django 2.2.10 on 2021-05-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptess', '0002_remove_account_cartecredit'),
        ('Cartes_Creditss', '0002_auto_20210508_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_card',
            name='compte',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comptess.Account'),
        ),
    ]
