# Generated by Django 2.2.10 on 2021-05-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_transaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
