# Generated by Django 2.2.10 on 2021-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_auto_20210505_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_pred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='etat',
            field=models.CharField(choices=[('En cours', 'En cours'), ('En traitement', 'En traitement'), ('Traitée', 'Traitée')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_fraud_pred',
            field=models.IntegerField(null=True),
        ),
    ]
