# Generated by Django 2.2.10 on 2021-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_auto_20210505_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='etat',
            field=models.CharField(choices=[('En traitement', 'En traitement'), ('Traitée', 'Traitée')], max_length=100, null=True),
        ),
    ]
