# Generated by Django 2.2.10 on 2021-05-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactiions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100, null=True)),
                ('amt', models.FloatField(null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('city_pop', models.IntegerField(null=True)),
                ('dob', models.CharField(max_length=100, null=True)),
                ('unix_time', models.IntegerField(null=True)),
                ('is_fraud', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('hours', models.IntegerField(null=True)),
                ('category_pred', models.CharField(max_length=100, null=True)),
                ('is_fraud_pred', models.IntegerField(null=True)),
                ('etat', models.CharField(choices=[('En traitement', 'En traitement'), ('Traitée', 'Traitée')], max_length=100, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptess.Account')),
            ],
        ),
    ]
