# Generated by Django 2.2.10 on 2021-05-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactiions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiions',
            name='compte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comptess.Account'),
        ),
    ]
