# Generated by Django 2.2.10 on 2021-05-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cartes_Creditss', '0003_credit_card_compte'),
        ('transactiions', '0002_auto_20210508_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiions',
            name='compte',
        ),
        migrations.AddField(
            model_name='transactiions',
            name='CarteCredit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cartes_Creditss.credit_card'),
        ),
    ]
