# Generated by Django 2.2.10 on 2021-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiions', '0004_remove_transactiions_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiions',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
