# Generated by Django 2.2.10 on 2021-05-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactiions', '0005_transactiions_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiions',
            name='etat',
        ),
    ]
